allowBuilds:
  '@sableclient/tauri-plugin-notifications-api': true
  '@sentry/cli': true
  '@swc/core': true
  cloudflared: true
  cpu-features: true
  esbuild: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
  workerd: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - 'matrix-js-sdk'
  - '@sableclient/sable-call-embedded'
  - '@sableclient/twemoji-font'

overrides:
  brace-expansion: '>=1.1.12'
  esbuild: '>=0.25.0'
  flatted: '>=3.4.2'
  jsdom>undici: '^7.28.0'
  lodash: '>=4.17.23'
  minimatch: '>=10.2.3'
  rollup: '>=4.59.0'
  serialize-javascript: '>=7.0.3'
  undici: '>=7.24.0'

peerDependencyRules:
  allowedVersions:
    'folds>@vanilla-extract/css': '1.18.0'
    'folds>@vanilla-extract/recipes': '0.5.7'
    'folds>classnames': '2.5.1'
    'folds>react': '18.3.1'
    'folds>react-dom': '18.3.1'
