name: Quality checks

on:
  pull_request:
  push:
    branches: [dev]
  merge_group:

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Check formatting
        run: pnpm run fmt:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Run Lint
        run: pnpm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Run TypeScript typecheck
        run: pnpm run typecheck --pretty false

  knip:
    name: Knip
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Run Knip
        run: pnpm run knip

  tests:
    name: Tests
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup app
        uses: ./.github/actions/setup

      - name: Run tests
        run: pnpm run test:run

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.head_ref != 'release'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup app and build
        uses: ./.github/actions/setup
        with:
          build: 'true'
